/**
 * npm run build:cigtags — the tags the landing row filters by.
 *
 *   public/cigpages/*.svg  ->  lib/cigtags.json
 *
 * Every cigarette's info page carries the same three closed vocabularies:
 * menthol (Y or N), harshness (Lite, mid or hard) and a pack price ($15,
 * $25 or $30). Those are the page's tags, and they are what the row's tag
 * buttons filter on. The page's other two fields — the tasting notes and
 * the three pairings — are open vocabularies (112 and 207 distinct values
 * across the set), so they cannot be a row of buttons and are left out.
 *
 * IT READS THE BUILT PAGES, NOT THE SOURCE VECTORS, and is therefore fast
 * (text, no rasters) where `build:cigpages` takes half an hour. The built
 * page is the artefact that actually ships and it carries the text verbatim,
 * so it is the honest thing to read. **Re-run this after `build:cigpages`.**
 *
 * THE MANIFEST IS KEYED BY PACK, NOT BY PAGE. The row is a row of packs and
 * twelve of them share a page with a name-twin, so the twin rule from
 * `lib/cigPages.ts` is applied here — the same key (lowercased, stripped of
 * everything but letters and digits) — and the result is asserted to cover
 * every pack. That way the client filters with one lookup and the page
 * manifest stays out of the browser bundle, which is why `lib/cigPages.ts`
 * is server-only in the first place.
 *
 * Anything unexpected is a hard error, like the other builds here: a page
 * whose menthol is not Y or N, or whose harshness is not one of the three,
 * means the design has changed and the vocabulary below has to change with
 * it — far better than a filter that quietly matches nothing.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

const PAGES = 'public/cigpages';
const OUT = 'lib/cigtags.json';

const MENTHOL = ['Y', 'N'];
const HARSHNESS = ['Lite', 'mid', 'hard'];

/** The owner's own text, as it sits in the page. */
const texts = (svg) =>
  [...svg.matchAll(/<text\b[^>]*>([\s\S]*?)<\/text>/g)].map((m) =>
    m[1]
      .replace(/&#x27;/g, "'")
      .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(+d))
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .trim(),
  );

const pages = new Map();
for (const file of readdirSync(PAGES).filter((f) => f.endsWith('.svg'))) {
  const id = file.replace(/\.svg$/, '');
  const t = texts(readFileSync(`${PAGES}/${file}`, 'utf8'));

  // the three labels run before their three values, in that order, on every
  // page — so the values are the three that follow the last label
  const at = t.indexOf('Possible Pairings');
  if (at < 0) throw new Error(`${id}: no "Possible Pairings" label`);
  const menthol = t[at + 1];
  const harshness = t[at + 2];
  if (!MENTHOL.includes(menthol)) throw new Error(`${id}: menthol is ${JSON.stringify(menthol)}, expected Y or N`);
  if (!HARSHNESS.includes(harshness)) throw new Error(`${id}: harshness is ${JSON.stringify(harshness)}, expected one of ${HARSHNESS.join(', ')}`);

  const priced = t.find((x) => /^\$\d+\/p$/.test(x));
  if (!priced) throw new Error(`${id}: no pack price`);
  const price = Number(priced.slice(1, -2));

  pages.set(id, { menthol, harshness, price });
}

// the twin rule, as lib/cigPages.ts applies it
const key = (s) => s.toLowerCase().replace(/[^a-z0-9]/g, '');
const packs = JSON.parse(readFileSync('lib/cigs.json', 'utf8')).packs;
const manifest = JSON.parse(readFileSync('lib/cigpages.json', 'utf8'));
const byName = new Map();
for (const page of manifest.pages) {
  const k = key(page.name);
  if (byName.has(k)) byName.get(k).push(page);
  else byName.set(k, [page]);
}

const tags = {};
const orphans = [];
for (const pack of packs) {
  let tag = pages.get(pack.id);
  if (!tag) {
    const match = byName.get(key(pack.name));
    if (match?.length === 1) tag = pages.get(match[0].id);
  }
  if (!tag) orphans.push(pack.id);
  else tags[pack.id] = tag;
}
if (orphans.length) throw new Error(`no tags for ${orphans.length} packs: ${orphans.slice(0, 6).join(', ')}`);

const tally = (field) => {
  const m = new Map();
  for (const t of Object.values(tags)) m.set(t[field], (m.get(t[field]) ?? 0) + 1);
  return [...m].sort((a, b) => b[1] - a[1]).map(([v, n]) => `${v} ${n}`).join(', ');
};

writeFileSync(
  OUT,
  `${JSON.stringify(
    {
      note: 'Generated by npm run build:cigtags from public/cigpages — do not edit by hand. Keyed by PACK id (twins resolved to their page). See scripts/build-cigtags.mjs.',
      count: Object.keys(tags).length,
      tags,
    },
    null,
    1,
  )}\n`,
);

console.log(`${pages.size} pages -> ${Object.keys(tags).length} packs tagged, wrote ${OUT}`);
console.log(`  menthol:   ${tally('menthol')}`);
console.log(`  harshness: ${tally('harshness')}`);
console.log(`  price:     ${tally('price')}`);
